theme = "identity"
disableKinds = ['taxonomy', 'term']
copyright = "2023 プロフィール.com"

baseURL = "https://xn--dck5ef6fh6g.com/sample3/"
title = "Sample3 | プロフィール.com"

[params]
author = "Jane Doe"
icon = "avatar"
description = "CONGUE PELLENTESQUE ELEIFEND"

[[params.social]]
name = "twitter"
icon = "brands fa-twitter"
url = "https://twitter.com/"

[[params.social]]
name = "instagram"
icon = "brands fa-instagram"
url = "https://www.instagram.com/"

[[params.social]]
name = "facebook"
icon = "brands fa-facebook"
url = "https://www.facebook.com/"
